import type { NextConfig } from "next";

const demo = process.env.NEXT_PUBLIC_DEMO !== "false";
// STATIC_EXPORT=1 builds plain files for Apache/DirectAdmin hosting (see scripts/build-static.mjs).
const staticExport = process.env.STATIC_EXPORT === "1";

const nextConfig: NextConfig = staticExport
  ? {
      output: "export",
      // No image server on shared hosting: sizes are pre-generated by scripts/optimize-images.mjs.
      images: { loader: "custom", loaderFile: "./lib/image-loader.ts" },
    }
  : {
      images: {
        formats: ["image/avif", "image/webp"],
        qualities: [70, 75],
      },
      async headers() {
        if (!demo) return [];
        return [{ source: "/:path*", headers: [{ key: "X-Robots-Tag", value: "noindex, nofollow" }] }];
      },
    };

export default nextConfig;
